### ISSUE TITLE
Cannot access the data

### ISSUE THREAD

**Issue by zijieli-Jlee** [microsoft/pdearena#15]
Thanks authors for this nice work including various datasets and models.
I came across the following issue when I was trying to download the pre-generated dataset:

```
> azcopy copy "https://pdearenarelease.blob.core.windows.net/datasets/NavierStokes2D_smoke" \
>             "./pde_data/" --recursive
INFO: Scanning...
INFO: Autologin not specified.

failed to perform copy command due to error: Login Credentials missing. No SAS token or OAuth token is present and the resource is not public
```

Any suggestion would be appreciated!

**Comment by rejuvyesh** [comment]
Unfortunately we lost access to our azure bucket. We are working on reuploading to huggingface and updating the docs.

**Comment by brandstetter-johannes** [comment]
We have uploaded the data here: https://huggingface.co/pdearena. An update of the docs is coming

**Comment by zijieli-Jlee** [comment]
Thanks!
