### ISSUE TITLE
Smoke_cond not actually using different bouyancies. 

### ISSUE THREAD

**Issue by mikemccabe210** [microsoft/pdearena#23]
Hi,

Thanks for providing the code for the data generation! It's very easy to use/modify. I noticed while generating the data that the code for the conditional N-S experiment isn't actually using the randomly sampled bouyancy. 

Currently it sets the bouyancy as:

`cfg.pdeconfig.buoyancy_y = bf.item()`

but the parameters are pulled from the namespace init_args, so it should actually be:

`cfg.pdeconfig.init_args.buoyancy_y = bf.item()'

It looks like the data downloadable via git lfs is affected by this as well. 

I'm happy to change it and submit a pull request if the maintainers are busy.

**Comment by rejuvyesh** [comment]
Oh no, you are absolutely right! Will get a fix and upload the dataset asap.

**Comment by brandstetter-johannes** [comment]
Thanks a lot for posting this @mikemccabe210. I have created a PR (https://github.com/microsoft/pdearena/pull/24), as soon as this is approved I will regenerate the data and upload to huggingface.

**Comment by brandstetter-johannes** [comment]
Data is regenerated and uploaded to huggingface. Again thanks for being so sharp and finding this bug.
