### ISSUE TITLE
TypeError on "pdeconfig.n_vector_components" when running scripts/train.py

### ISSUE THREAD

**Issue by xwqok** [microsoft/pdearena#26]
Hello,

I encountered an error while trying to run the **python scripts/train.py -c <path/to/config>**. The whole command line just like this photo   
<img width="797" alt="image" src="https://github.com/microsoft/pdearena/assets/29054010/06e7742e-c204-4b3d-b979-f735edf59049">

Below is the traceback I received:

`Traceback (most recent call last):
  ... [trimmed for brevity]
TypeError: Parser key "model": Problem with given class_path "pdearena.models.pdemodel.PDEModel":
  - Configuration check failed :: Key "pdeconfig.n_vector_components" is required but not included in config object or its value is None.
`
Environment:
OS:Linux Ubuntu 20.04
Python Version: 3.8
Package Version: pytorch 1.12.1, cuda 11.3

I've looked into the traceback and the code but couldn't find a way to resolve the issue myself. I'm confused about why the "pdeconfig.n_vector_components" key is missing or set to None in the configuration object. Could you please help me look into this?

Thank you for your time and assistance.

**Comment by rejuvyesh** [comment]
Can you also share your pytorch-lightning version?

**Comment by xwqok** [comment]
> Can you also share your pytorch-lightning version? Also can you share the full error trace. It's very likely an issue with our `parser.link_arguments` in `pdearena/utils.py`.

Hi, thank you for your response. Indeed, the issue was related to the pytorch-lightning version. After reinstalling pytorch-lightning, the problem has been resolved. This is a superb project! I hope there will be more detailed tutorials on pdemodel in the future.

**Comment by rejuvyesh** [comment]
Could you still share the pytorch-lightning version please? We want to make sure our dependency version/conda environment works correctly.

**Comment by xwqok** [comment]
I apologize as I did not accurately record the initial version of pytorch-lightning that I was using. I can confirm that I encountered compatibility errors with pytorch-lightning==1.8.0. However, I am certain that the issue was resolved when I upgraded to pytorch-lightning>=2.0.0.
